### ISSUE TITLE
RegisterPage

### ISSUE THREAD

**Issue by Hameedarh** [NECA-ITF/trainee-attendance#4]
MUST HAVE

1. Full name input
2. Phone number input
3. Email address input
4. gender selection
5. Passsword input
6. Confirm password input
7. Department selection

**Comment by Harry654** [comment]
We are all strictly using functional components right?

**Comment by olaniyiisrael** [comment]
Ok.

**Comment by olaniyiisrael** [comment]
Ok.

**Comment by olaniyiisrael** [comment]
Ok.

**Comment by olaniyiisrael** [comment]
Ok.
